@baseUrl = http://localhost:3000
@accessToken = {{signin.response.body.accessToken}}
@bankAccountId = {{{list_bank_accounts.response.body.id}}}

# @name register
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name": "Gustavo Dias",
    "email": "gustavodiasa2121@gmail.com",
    "password": "password123"
}

###

# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "gustavodiasa2121@gmail.com",
    "password": "password123"
}
###

# @name me
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name list_categories
GET {{baseUrl}}/transaction-categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name create_bank_account
POST {{baseUrl}}/bank-accounts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Nubank",
    "initialBalance": 1500,
    "color": "#7950F2",
    "type": "CHECKING"
}

###

# @name list_bank_accounts
GET {{baseUrl}}/bank-accounts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name update_bank_account
PUT {{baseUrl}}/bank-accounts/deeb2419-fec4-41cd-836c-41bcb4124852
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Nubank",
    "initialBalance": 2500,
    "color": "#7950F2",
    "type": "CHECKING"
}

###

# @name delete_bank_account
DELETE {{baseUrl}}/bank-accounts/231a4150-194d-40d5-a843-03114eef7053
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name list_transactions
GET {{baseUrl}}/transactions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name create_transaction
POST {{baseUrl}}/transactions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}

###

# @name update_transactions
PUT {{baseUrl}}/transactions/KKK
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}

###

# @name delete_transactions
DELETE {{baseUrl}}/transactions/KKK
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{}