@baseUrl = http://localhost:3000
@accessToken = {{signin.response.body.accessToken}}
@bankAccountId = {{{create_bank_account.response.body.id}}}

# @name register
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name": "Gustavo Dias",
    "email": "gustavodiasa2121@gmail.com",
    "password": "password123"
}

###

# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "gustavodiasa2121@gmail.com",
    "password": "password123"
}
###

# @name me
GET {{baseUrl}}/users/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name list_categories
GET {{baseUrl}}/transaction-categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name create_bank_account
POST {{baseUrl}}/bank-accounts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Nubank",
    "initialBalance": 1500,
    "color": "#7950F2",
    "type": "CHECKING"
}

###

# @name list_bank_accounts
GET {{baseUrl}}/bank-accounts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name update_bank_account
PUT {{baseUrl}}/bank-accounts/deeb2419-fec4-41cd-836c-41bcb4124852
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Nubank",
    "initialBalance": 2500,
    "color": "#7950F2",
    "type": "CHECKING"
}

###

# @name delete_bank_account
DELETE {{baseUrl}}/bank-accounts/231a4150-194d-40d5-a843-03114eef7053
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name list_transactions
GET {{baseUrl}}/transactions?month=7&year=2024&bankAccountId=5e6cf8c3-e23c-4cb5-b326-27d5b477a4df&type=EXPENSE
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# @name create_transaction
POST {{baseUrl}}/transactions
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "bankAccountId": "5e6cf8c3-e23c-4cb5-b326-27d5b477a4df",
  "categoryId": "184c4d11-3e82-4bde-b822-eb26c9b011eb",
  "name": "Aug Salary",
  "value": 6000,
  "date": "2024-08-25T12:04:22.845Z",
  "type": "EXPENSE"
}

###

# @name update_transactions
PUT {{baseUrl}}/transactions/366aa918-5b64-4d3d-97c7-0a3b08d5d8c4
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Aug Salary",
  "value": 7500,
  "date": "2024-08-25T12:04:22.845Z",
  "type": "INCOME",
  "bankAccountId": "6ca2c2b9-353c-4b9e-9dd0-72eeb08bd308",
  "categoryId": "184c4d11-3e82-4bde-b822-eb26c9b011eb"
}

###

# @name delete_transactions
DELETE {{baseUrl}}/transactions/feed0c7e-0304-470e-8949-c079195fc804
Authorization: Bearer {{accessToken}}
Content-Type: application/json
